name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Astro check
        run: pnpm check
      - name: ESlint
        run: pnpm lint
      - name: Prettier
        run: pnpm format:check
      - name: Build
        run: pnpm build
